#!/bin/bash

MOD_HOME="/var/smoothwall/mods/adv_fw_stats"
DB="${MOD_HOME}/var/db/fwstats.db"

/usr/bin/sqlite3 $DB "SELECT name,SUM(hitcount) FROM ifaces GROUP BY name ORDER BY SUM(hitcount) DESC" | sed -e 's/|/=/'
/usr/bin/sqlite3 $DB "SELECT name,SUM(hitcount) FROM filters GROUP BY name ORDER BY SUM(hitcount) DESC" | sed -e 's/|/=/'
/usr/bin/sqlite3 $DB "SELECT ip_addr,SUM(hitcount) FROM sources GROUP BY ip_addr ORDER BY SUM(hitcount) DESC LIMIT 5" | sed -e 's/|/=/'
/usr/bin/sqlite3 $DB "SELECT ip_addr,SUM(hitcount) FROM destinations GROUP BY ip_addr ORDER BY SUM(hitcount) DESC LIMIT 5" | sed -e 's/|/=/'
/usr/bin/sqlite3 $DB "SELECT port_num,SUM(hitcount) from dest_ports GROUP BY port_num ORDER BY SUM(hitcount) DESC LIMIT 5" | sed -e 's/|/=/'

